// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8FpvyNWPQ-QHyIIuHenY2L9SBezzXVo',
    appId: '1:656548803634:android:fff630209dec40c4d3f82b',
    messagingSenderId: '656548803634',
    projectId: 'clozzr-b9a52',
    storageBucket: 'clozzr-b9a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAitg-cI3RZ1-qKitod0Xcerdxkc7ytns',
    appId: '1:656548803634:ios:44a3ffa13422c2b4d3f82b',
    messagingSenderId: '656548803634',
    projectId: 'clozzr-b9a52',
    storageBucket: 'clozzr-b9a52.appspot.com',
    iosClientId: '656548803634-bas31v3umd2m4k2jc1f9o7q92ls5ubf2.apps.googleusercontent.com',
    iosBundleId: 'com.remotcare.clozze',
  );
}
